python3 ./code/run_robust_dp_mnist.py --train --BATCH_SIZE 128 --BATCHES_PER_LOT 1\
    --EVAL_TRAIN_FREQUENCY 100 --EVAL_VALID_FREQUENCY 20\
    --NUM_EPOCHS 200 --NUM_CLASSES 10 --load_model=False\
    --DATA_DIR ../mnist \
    --LEARNING_RATE 5e-2 --LEARNING_DECAY_RATE 0.98 --LEARNING_DECAY_STEPS 100\
    --ATTACK_SIZE 1.0 --ROBUST_SIGMA 0.5 --ROBUST_SAMPLING_N 2000\
    --MAX_ITERATIONS 800000 --NO_DP_SGD=True\
    --TOTAL_EPS 1.0 --DP_GRAD_CLIPPING_L2NORM 1.0\
    --MAX_NOISE_DELTA 1e-5 --G_LIP 0.5 --K_SCONVEX 50.0 --LOSS_LOWER_BOUND 1e-2\
    --MAX_SGD_DELTA 0.0